services:
  postgres:
    image: postgres:15.2
    container_name: postgres
    restart: always
    environment:
      TZ: America/Sao_Paulo
    env_file:
      - .env
    volumes:
      - database:/var/lib/postgresql/data

  web:
    build: .
    working_dir: /app
    container_name: web
    ports:
      - 3000:3000
    command: bash -c "rm -f tmp/pids/server.pid && bin/setup && rails s -b 0.0.0.0"
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_started
    links:
      - mailcatcher

  mailcatcher:
    image: yappabe/mailcatcher
    ports:
      - "1026:1025" # Alterei para 1026 para SMTP
      - "1081:1080" # Alterei para 1081 para a interface web
    command: mailcatcher --no-quit --foreground --ip=0.0.0.0

volumes:
  database:
  rubygems:
